from test import api_tester
from test.api import test_bmp_api
from test.api import test_crop_api
from test.api import test_emf_api
from test.api import test_examples
from test.api import test_frames_get_api
from test.api import test_frames_post_api
from test.api import test_gif_api
from test.api import test_jpeg2000_api
from test.api import test_jpg_api
from test.api import test_psd_api
from test.api import test_resize_api
from test.api import test_rotate_flip_api
from test.api import test_save_as_api
from test.api import test_tiff_api
from test.api import test_update_image_api
from test.api import test_web_p_api
from test.api import test_wmf_api
from test.api.AI import test_compare_images
from test.api.AI import test_find_duplicates
from test.api.AI import test_find_images
from test.api.AI import test_search_context
from test.api.storage import test_file_api
from test.api.storage import test_folder_api
from test.api.storage import test_storage_api
