# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.imaging_api import ImagingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImagingApi(unittest.TestCase):
    """ImagingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.imaging_api.ImagingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_file(self):
        """Test case for copy_file

        Copy file  # noqa: E501
        """
        pass

    def test_copy_folder(self):
        """Test case for copy_folder

        Copy folder  # noqa: E501
        """
        pass

    def test_create_folder(self):
        """Test case for create_folder

        Create the folder  # noqa: E501
        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Delete file  # noqa: E501
        """
        pass

    def test_delete_folder(self):
        """Test case for delete_folder

        Delete folder  # noqa: E501
        """
        pass

    def test_delete_search_context(self):
        """Test case for delete_search_context

        Deletes the search context.  # noqa: E501
        """
        pass

    def test_delete_search_context_image(self):
        """Test case for delete_search_context_image

        Delete image and images features from search context  # noqa: E501
        """
        pass

    def test_delete_search_context_image_features(self):
        """Test case for delete_search_context_image_features

        Deletes image features from search context.  # noqa: E501
        """
        pass

    def test_download_file(self):
        """Test case for download_file

        Download file  # noqa: E501
        """
        pass

    def test_get_disc_usage(self):
        """Test case for get_disc_usage

        Get disc usage  # noqa: E501
        """
        pass

    def test_get_file_versions(self):
        """Test case for get_file_versions

        Get file versions  # noqa: E501
        """
        pass

    def test_get_files_list(self):
        """Test case for get_files_list

        Get all files and folders within a folder  # noqa: E501
        """
        pass

    def test_get_image_bmp(self):
        """Test case for get_image_bmp

        Update parameters of existing BMP image.  # noqa: E501
        """
        pass

    def test_get_image_crop(self):
        """Test case for get_image_crop

        Crop an existing image.  # noqa: E501
        """
        pass

    def test_get_image_emf(self):
        """Test case for get_image_emf

        Process existing EMF imaging using given parameters.  # noqa: E501
        """
        pass

    def test_get_image_frame(self):
        """Test case for get_image_frame

        Get separate frame from existing TIFF image.  # noqa: E501
        """
        pass

    def test_get_image_frame_properties(self):
        """Test case for get_image_frame_properties

        Get separate frame properties of existing TIFF image.  # noqa: E501
        """
        pass

    def test_get_image_gif(self):
        """Test case for get_image_gif

        Update parameters of existing GIF image.  # noqa: E501
        """
        pass

    def test_get_image_jpeg2000(self):
        """Test case for get_image_jpeg2000

        Update parameters of existing JPEG2000 image.  # noqa: E501
        """
        pass

    def test_get_image_jpg(self):
        """Test case for get_image_jpg

        Update parameters of existing JPEG image.  # noqa: E501
        """
        pass

    def test_get_image_properties(self):
        """Test case for get_image_properties

        Get properties of an image.  # noqa: E501
        """
        pass

    def test_get_image_psd(self):
        """Test case for get_image_psd

        Update parameters of existing PSD image.  # noqa: E501
        """
        pass

    def test_get_image_resize(self):
        """Test case for get_image_resize

        Resize an existing image.  # noqa: E501
        """
        pass

    def test_get_image_rotate_flip(self):
        """Test case for get_image_rotate_flip

        Rotate and/or flip an existing image.  # noqa: E501
        """
        pass

    def test_get_image_save_as(self):
        """Test case for get_image_save_as

        Export existing image to another format.  # noqa: E501
        """
        pass

    def test_get_image_tiff(self):
        """Test case for get_image_tiff

        Update parameters of existing TIFF image.  # noqa: E501
        """
        pass

    def test_get_image_update(self):
        """Test case for get_image_update

        Perform scaling, cropping and flipping of an existing image in a single request.  # noqa: E501
        """
        pass

    def test_get_image_web_p(self):
        """Test case for get_image_web_p

        Update parameters of existing WEBP image.  # noqa: E501
        """
        pass

    def test_get_image_wmf(self):
        """Test case for get_image_wmf

        Process existing WMF image using given parameters.  # noqa: E501
        """
        pass

    def test_get_search_context_extract_image_features(self):
        """Test case for get_search_context_extract_image_features

        Extract features from image without adding to search context. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_get_search_context_find_duplicates(self):
        """Test case for get_search_context_find_duplicates

        Find images duplicates.  # noqa: E501
        """
        pass

    def test_get_search_context_find_similar(self):
        """Test case for get_search_context_find_similar

        Find similar images. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_get_search_context_image(self):
        """Test case for get_search_context_image

        Get image from search context  # noqa: E501
        """
        pass

    def test_get_search_context_image_features(self):
        """Test case for get_search_context_image_features

        Gets image features from search context.  # noqa: E501
        """
        pass

    def test_get_search_context_status(self):
        """Test case for get_search_context_status

        Gets the search context status.  # noqa: E501
        """
        pass

    def test_get_tiff_to_fax(self):
        """Test case for get_tiff_to_fax

        Update parameters of existing TIFF image accordingly to fax parameters.  # noqa: E501
        """
        pass

    def test_move_file(self):
        """Test case for move_file

        Move file  # noqa: E501
        """
        pass

    def test_move_folder(self):
        """Test case for move_folder

        Move folder  # noqa: E501
        """
        pass

    def test_object_exists(self):
        """Test case for object_exists

        Check if file or folder exists  # noqa: E501
        """
        pass

    def test_post_create_search_context(self):
        """Test case for post_create_search_context

        Create new search context.  # noqa: E501
        """
        pass

    def test_post_image_bmp(self):
        """Test case for post_image_bmp

        Update parameters of BMP image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_crop(self):
        """Test case for post_image_crop

        Crop an image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_emf(self):
        """Test case for post_image_emf

        Process existing EMF imaging using given parameters. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_frame(self):
        """Test case for post_image_frame

        Get separate frame from existing TIFF image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_frame_properties(self):
        """Test case for post_image_frame_properties

        Get separate frame properties of existing TIFF image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_gif(self):
        """Test case for post_image_gif

        Update parameters of GIF image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_jpeg2000(self):
        """Test case for post_image_jpeg2000

        Update parameters of JPEG2000 image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_jpg(self):
        """Test case for post_image_jpg

        Update parameters of JPEG image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_properties(self):
        """Test case for post_image_properties

        Get properties of an image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_psd(self):
        """Test case for post_image_psd

        Update parameters of PSD image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_resize(self):
        """Test case for post_image_resize

        Resize an image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_rotate_flip(self):
        """Test case for post_image_rotate_flip

        Rotate and/or flip an image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_save_as(self):
        """Test case for post_image_save_as

        Export existing image to another format. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.               # noqa: E501
        """
        pass

    def test_post_image_tiff(self):
        """Test case for post_image_tiff

        Update parameters of TIFF image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_update(self):
        """Test case for post_image_update

        Perform scaling, cropping and flipping of an image in a single request. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.               # noqa: E501
        """
        pass

    def test_post_image_web_p(self):
        """Test case for post_image_web_p

        Update parameters of WEBP image. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_image_wmf(self):
        """Test case for post_image_wmf

        Process existing WMF image using given parameters. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_search_context_add_image(self):
        """Test case for post_search_context_add_image

        Add image and images features to search context. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_search_context_add_tag(self):
        """Test case for post_search_context_add_tag

        Add tag and reference image to search context. Image data is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_search_context_compare_images(self):
        """Test case for post_search_context_compare_images

        Compare two images. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_search_context_extract_image_features(self):
        """Test case for post_search_context_extract_image_features

        Extract images features and add them to search context. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_search_context_find_by_tags(self):
        """Test case for post_search_context_find_by_tags

        Find images by tags. Tags JSON string is passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_post_tiff_append(self):
        """Test case for post_tiff_append

        Appends existing TIFF image to another existing TIFF image (i.e. merges TIFF images).  # noqa: E501
        """
        pass

    def test_put_search_context_image(self):
        """Test case for put_search_context_image

        Update image and images features in search context. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_put_search_context_image_features(self):
        """Test case for put_search_context_image_features

        Update images features in search context. Image data may be passed as zero-indexed multipart/form-data content or as raw body stream.  # noqa: E501
        """
        pass

    def test_storage_exists(self):
        """Test case for storage_exists

        Check if storage exists  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        Upload file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
