# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.object_exist import ObjectExist  # noqa: E501
from swagger_client.rest import ApiException


class TestObjectExist(unittest.TestCase):
    """ObjectExist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectExist(self):
        """Test ObjectExist"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.object_exist.ObjectExist()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
