from asposeimagingcloud.models.requests.copy_file_request import CopyFileRequest
from asposeimagingcloud.models.requests.copy_folder_request import CopyFolderRequest
from asposeimagingcloud.models.requests.create_folder_request import CreateFolderRequest
from asposeimagingcloud.models.requests.delete_file_request import DeleteFileRequest
from asposeimagingcloud.models.requests.delete_folder_request import DeleteFolderRequest
from asposeimagingcloud.models.requests.delete_search_context_image_features_request import \
    DeleteSearchContextImageFeaturesRequest
from asposeimagingcloud.models.requests.delete_search_context_image_request import DeleteSearchContextImageRequest
from asposeimagingcloud.models.requests.delete_search_context_request import DeleteSearchContextRequest
from asposeimagingcloud.models.requests.download_file_request import DownloadFileRequest
from asposeimagingcloud.models.requests.get_disc_usage_request import GetDiscUsageRequest
from asposeimagingcloud.models.requests.get_file_versions_request import GetFileVersionsRequest
from asposeimagingcloud.models.requests.get_files_list_request import GetFilesListRequest
from asposeimagingcloud.models.requests.get_image_bmp_request import GetImageBmpRequest
from asposeimagingcloud.models.requests.get_image_crop_request import GetImageCropRequest
from asposeimagingcloud.models.requests.get_image_emf_request import GetImageEmfRequest
from asposeimagingcloud.models.requests.get_image_frame_properties_request import GetImageFramePropertiesRequest
from asposeimagingcloud.models.requests.get_image_frame_request import GetImageFrameRequest
from asposeimagingcloud.models.requests.get_image_gif_request import GetImageGifRequest
from asposeimagingcloud.models.requests.get_image_jpeg2000_request import GetImageJpeg2000Request
from asposeimagingcloud.models.requests.get_image_jpg_request import GetImageJpgRequest
from asposeimagingcloud.models.requests.get_image_properties_request import GetImagePropertiesRequest
from asposeimagingcloud.models.requests.get_image_psd_request import GetImagePsdRequest
from asposeimagingcloud.models.requests.get_image_resize_request import GetImageResizeRequest
from asposeimagingcloud.models.requests.get_image_rotate_flip_request import GetImageRotateFlipRequest
from asposeimagingcloud.models.requests.get_image_save_as_request import GetImageSaveAsRequest
from asposeimagingcloud.models.requests.get_image_tiff_request import GetImageTiffRequest
from asposeimagingcloud.models.requests.get_image_update_request import GetImageUpdateRequest
from asposeimagingcloud.models.requests.get_image_web_p_request import GetImageWebPRequest
from asposeimagingcloud.models.requests.get_image_wmf_request import GetImageWmfRequest
from asposeimagingcloud.models.requests.get_search_context_extract_image_features_request import \
    GetSearchContextExtractImageFeaturesRequest
from asposeimagingcloud.models.requests.get_search_context_find_duplicates_request import \
    GetSearchContextFindDuplicatesRequest
from asposeimagingcloud.models.requests.get_search_context_find_similar_request import \
    GetSearchContextFindSimilarRequest
from asposeimagingcloud.models.requests.get_search_context_image_features_request import \
    GetSearchContextImageFeaturesRequest
from asposeimagingcloud.models.requests.get_search_context_image_request import GetSearchContextImageRequest
from asposeimagingcloud.models.requests.get_search_context_status_request import GetSearchContextStatusRequest
from asposeimagingcloud.models.requests.get_tiff_to_fax_request import GetTiffToFaxRequest
from asposeimagingcloud.models.requests.move_file_request import MoveFileRequest
from asposeimagingcloud.models.requests.move_folder_request import MoveFolderRequest
from asposeimagingcloud.models.requests.object_exists_request import ObjectExistsRequest
from asposeimagingcloud.models.requests.post_create_search_context_request import PostCreateSearchContextRequest
from asposeimagingcloud.models.requests.post_image_bmp_request import PostImageBmpRequest
from asposeimagingcloud.models.requests.post_image_crop_request import PostImageCropRequest
from asposeimagingcloud.models.requests.post_image_emf_request import PostImageEmfRequest
from asposeimagingcloud.models.requests.post_image_frame_properties_request import PostImageFramePropertiesRequest
from asposeimagingcloud.models.requests.post_image_frame_request import PostImageFrameRequest
from asposeimagingcloud.models.requests.post_image_gif_request import PostImageGifRequest
from asposeimagingcloud.models.requests.post_image_jpeg2000_request import PostImageJpeg2000Request
from asposeimagingcloud.models.requests.post_image_jpg_request import PostImageJpgRequest
from asposeimagingcloud.models.requests.post_image_properties_request import PostImagePropertiesRequest
from asposeimagingcloud.models.requests.post_image_psd_request import PostImagePsdRequest
from asposeimagingcloud.models.requests.post_image_resize_request import PostImageResizeRequest
from asposeimagingcloud.models.requests.post_image_rotate_flip_request import PostImageRotateFlipRequest
from asposeimagingcloud.models.requests.post_image_save_as_request import PostImageSaveAsRequest
from asposeimagingcloud.models.requests.post_image_tiff_request import PostImageTiffRequest
from asposeimagingcloud.models.requests.post_image_update_request import PostImageUpdateRequest
from asposeimagingcloud.models.requests.post_image_web_p_request import PostImageWebPRequest
from asposeimagingcloud.models.requests.post_image_wmf_request import PostImageWmfRequest
from asposeimagingcloud.models.requests.post_search_context_add_image_request import PostSearchContextAddImageRequest
from asposeimagingcloud.models.requests.post_search_context_add_tag_request import PostSearchContextAddTagRequest
from asposeimagingcloud.models.requests.post_search_context_compare_images_request import \
    PostSearchContextCompareImagesRequest
from asposeimagingcloud.models.requests.post_search_context_extract_image_features_request import \
    PostSearchContextExtractImageFeaturesRequest
from asposeimagingcloud.models.requests.post_search_context_find_by_tags_request import \
    PostSearchContextFindByTagsRequest
from asposeimagingcloud.models.requests.post_tiff_append_request import PostTiffAppendRequest
from asposeimagingcloud.models.requests.put_search_context_image_features_request import \
    PutSearchContextImageFeaturesRequest
from asposeimagingcloud.models.requests.put_search_context_image_request import PutSearchContextImageRequest
from asposeimagingcloud.models.requests.storage_exists_request import StorageExistsRequest
from asposeimagingcloud.models.requests.upload_file_request import UploadFileRequest

