# coding: utf-8

# flake8: noqa
"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.bmp_properties import BmpProperties
from swagger_client.models.dicom_properties import DicomProperties
from swagger_client.models.disc_usage import DiscUsage
from swagger_client.models.djvu_properties import DjvuProperties
from swagger_client.models.dng_properties import DngProperties
from swagger_client.models.error import Error
from swagger_client.models.error_details import ErrorDetails
from swagger_client.models.exif_data import ExifData
from swagger_client.models.file_versions import FileVersions
from swagger_client.models.files_list import FilesList
from swagger_client.models.files_upload_result import FilesUploadResult
from swagger_client.models.gif_properties import GifProperties
from swagger_client.models.image_duplicates import ImageDuplicates
from swagger_client.models.image_duplicates_set import ImageDuplicatesSet
from swagger_client.models.image_features import ImageFeatures
from swagger_client.models.imaging_response import ImagingResponse
from swagger_client.models.jfif_data import JfifData
from swagger_client.models.jpeg2000_properties import Jpeg2000Properties
from swagger_client.models.jpeg_properties import JpegProperties
from swagger_client.models.object_exist import ObjectExist
from swagger_client.models.odg_metadata import OdgMetadata
from swagger_client.models.odg_page import OdgPage
from swagger_client.models.odg_properties import OdgProperties
from swagger_client.models.png_properties import PngProperties
from swagger_client.models.psd_properties import PsdProperties
from swagger_client.models.search_context_status import SearchContextStatus
from swagger_client.models.search_result import SearchResult
from swagger_client.models.search_results_set import SearchResultsSet
from swagger_client.models.storage_exist import StorageExist
from swagger_client.models.storage_file import StorageFile
from swagger_client.models.tiff_frame import TiffFrame
from swagger_client.models.tiff_options import TiffOptions
from swagger_client.models.tiff_properties import TiffProperties
from swagger_client.models.web_p_properties import WebPProperties
from swagger_client.models.file_version import FileVersion
from swagger_client.models.jpeg_exif_data import JpegExifData
