# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.search_result import SearchResult  # noqa: F401,E501


class ImageDuplicates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duplicate_images': 'list[SearchResult]'
    }

    attribute_map = {
        'duplicate_images': 'DuplicateImages'
    }

    def __init__(self, duplicate_images=None):  # noqa: E501
        """ImageDuplicates - a model defined in Swagger"""  # noqa: E501

        self._duplicate_images = None
        self.discriminator = None

        if duplicate_images is not None:
            self.duplicate_images = duplicate_images

    @property
    def duplicate_images(self):
        """Gets the duplicate_images of this ImageDuplicates.  # noqa: E501

        Gets or sets the duplicate images.  # noqa: E501

        :return: The duplicate_images of this ImageDuplicates.  # noqa: E501
        :rtype: list[SearchResult]
        """
        return self._duplicate_images

    @duplicate_images.setter
    def duplicate_images(self, duplicate_images):
        """Sets the duplicate_images of this ImageDuplicates.

        Gets or sets the duplicate images.  # noqa: E501

        :param duplicate_images: The duplicate_images of this ImageDuplicates.  # noqa: E501
        :type: list[SearchResult]
        """

        self._duplicate_images = duplicate_images

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageDuplicates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageDuplicates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
