# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.image_duplicates import ImageDuplicates  # noqa: F401,E501


class ImageDuplicatesSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duplicates': 'list[ImageDuplicates]'
    }

    attribute_map = {
        'duplicates': 'Duplicates'
    }

    def __init__(self, duplicates=None):  # noqa: E501
        """ImageDuplicatesSet - a model defined in Swagger"""  # noqa: E501

        self._duplicates = None
        self.discriminator = None

        if duplicates is not None:
            self.duplicates = duplicates

    @property
    def duplicates(self):
        """Gets the duplicates of this ImageDuplicatesSet.  # noqa: E501

        Gets the duplicate images.  # noqa: E501

        :return: The duplicates of this ImageDuplicatesSet.  # noqa: E501
        :rtype: list[ImageDuplicates]
        """
        return self._duplicates

    @duplicates.setter
    def duplicates(self, duplicates):
        """Sets the duplicates of this ImageDuplicatesSet.

        Gets the duplicate images.  # noqa: E501

        :param duplicates: The duplicates of this ImageDuplicatesSet.  # noqa: E501
        :type: list[ImageDuplicates]
        """

        self._duplicates = duplicates

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageDuplicatesSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageDuplicatesSet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
