# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Jpeg2000Properties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comments': 'list[str]',
        'codec': 'str'
    }

    attribute_map = {
        'comments': 'Comments',
        'codec': 'Codec'
    }

    def __init__(self, comments=None, codec=None):  # noqa: E501
        """Jpeg2000Properties - a model defined in Swagger"""  # noqa: E501

        self._comments = None
        self._codec = None
        self.discriminator = None

        if comments is not None:
            self.comments = comments
        if codec is not None:
            self.codec = codec

    @property
    def comments(self):
        """Gets the comments of this Jpeg2000Properties.  # noqa: E501

        Gets or sets the JPEG comment markers.  # noqa: E501

        :return: The comments of this Jpeg2000Properties.  # noqa: E501
        :rtype: list[str]
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this Jpeg2000Properties.

        Gets or sets the JPEG comment markers.  # noqa: E501

        :param comments: The comments of this Jpeg2000Properties.  # noqa: E501
        :type: list[str]
        """

        self._comments = comments

    @property
    def codec(self):
        """Gets the codec of this Jpeg2000Properties.  # noqa: E501

        Gets or sets the JPEG2000 codec  # noqa: E501

        :return: The codec of this Jpeg2000Properties.  # noqa: E501
        :rtype: str
        """
        return self._codec

    @codec.setter
    def codec(self, codec):
        """Sets the codec of this Jpeg2000Properties.

        Gets or sets the JPEG2000 codec  # noqa: E501

        :param codec: The codec of this Jpeg2000Properties.  # noqa: E501
        :type: str
        """

        self._codec = codec

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Jpeg2000Properties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Jpeg2000Properties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
