# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WebPProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lossless': 'bool',
        'quality': 'float',
        'anim_loop_count': 'int',
        'anim_background_color': 'int'
    }

    attribute_map = {
        'lossless': 'Lossless',
        'quality': 'Quality',
        'anim_loop_count': 'AnimLoopCount',
        'anim_background_color': 'AnimBackgroundColor'
    }

    def __init__(self, lossless=None, quality=None, anim_loop_count=None, anim_background_color=None):  # noqa: E501
        """WebPProperties - a model defined in Swagger"""  # noqa: E501

        self._lossless = None
        self._quality = None
        self._anim_loop_count = None
        self._anim_background_color = None
        self.discriminator = None

        self.lossless = lossless
        self.quality = quality
        self.anim_loop_count = anim_loop_count
        self.anim_background_color = anim_background_color

    @property
    def lossless(self):
        """Gets the lossless of this WebPProperties.  # noqa: E501

        Gets or sets a value indicating whether these WebPOptions is lossless.  # noqa: E501

        :return: The lossless of this WebPProperties.  # noqa: E501
        :rtype: bool
        """
        return self._lossless

    @lossless.setter
    def lossless(self, lossless):
        """Sets the lossless of this WebPProperties.

        Gets or sets a value indicating whether these WebPOptions is lossless.  # noqa: E501

        :param lossless: The lossless of this WebPProperties.  # noqa: E501
        :type: bool
        """
        if lossless is None:
            raise ValueError("Invalid value for `lossless`, must not be `None`")  # noqa: E501

        self._lossless = lossless

    @property
    def quality(self):
        """Gets the quality of this WebPProperties.  # noqa: E501

        Gets or sets the quality.  # noqa: E501

        :return: The quality of this WebPProperties.  # noqa: E501
        :rtype: float
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this WebPProperties.

        Gets or sets the quality.  # noqa: E501

        :param quality: The quality of this WebPProperties.  # noqa: E501
        :type: float
        """
        if quality is None:
            raise ValueError("Invalid value for `quality`, must not be `None`")  # noqa: E501

        self._quality = quality

    @property
    def anim_loop_count(self):
        """Gets the anim_loop_count of this WebPProperties.  # noqa: E501

        Gets or sets the animation loop count.  # noqa: E501

        :return: The anim_loop_count of this WebPProperties.  # noqa: E501
        :rtype: int
        """
        return self._anim_loop_count

    @anim_loop_count.setter
    def anim_loop_count(self, anim_loop_count):
        """Sets the anim_loop_count of this WebPProperties.

        Gets or sets the animation loop count.  # noqa: E501

        :param anim_loop_count: The anim_loop_count of this WebPProperties.  # noqa: E501
        :type: int
        """
        if anim_loop_count is None:
            raise ValueError("Invalid value for `anim_loop_count`, must not be `None`")  # noqa: E501

        self._anim_loop_count = anim_loop_count

    @property
    def anim_background_color(self):
        """Gets the anim_background_color of this WebPProperties.  # noqa: E501

        Gets or sets the color of the animation background.  # noqa: E501

        :return: The anim_background_color of this WebPProperties.  # noqa: E501
        :rtype: int
        """
        return self._anim_background_color

    @anim_background_color.setter
    def anim_background_color(self, anim_background_color):
        """Sets the anim_background_color of this WebPProperties.

        Gets or sets the color of the animation background.  # noqa: E501

        :param anim_background_color: The anim_background_color of this WebPProperties.  # noqa: E501
        :type: int
        """
        if anim_background_color is None:
            raise ValueError("Invalid value for `anim_background_color`, must not be `None`")  # noqa: E501

        self._anim_background_color = anim_background_color

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebPProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebPProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
