# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DjvuProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'background_color': 'str',
        'has_background_color': 'bool',
        'pages_count': 'int'
    }

    attribute_map = {
        'background_color': 'BackgroundColor',
        'has_background_color': 'HasBackgroundColor',
        'pages_count': 'PagesCount'
    }

    def __init__(self, background_color=None, has_background_color=None, pages_count=None):  # noqa: E501
        """DjvuProperties - a model defined in Swagger"""  # noqa: E501

        self._background_color = None
        self._has_background_color = None
        self._pages_count = None
        self.discriminator = None

        if background_color is not None:
            self.background_color = background_color
        self.has_background_color = has_background_color
        self.pages_count = pages_count

    @property
    def background_color(self):
        """Gets the background_color of this DjvuProperties.  # noqa: E501

        Gets or sets background color.  # noqa: E501

        :return: The background_color of this DjvuProperties.  # noqa: E501
        :rtype: str
        """
        return self._background_color

    @background_color.setter
    def background_color(self, background_color):
        """Sets the background_color of this DjvuProperties.

        Gets or sets background color.  # noqa: E501

        :param background_color: The background_color of this DjvuProperties.  # noqa: E501
        :type: str
        """

        self._background_color = background_color

    @property
    def has_background_color(self):
        """Gets the has_background_color of this DjvuProperties.  # noqa: E501

        Gets or sets a value indicating whether background color is used.  # noqa: E501

        :return: The has_background_color of this DjvuProperties.  # noqa: E501
        :rtype: bool
        """
        return self._has_background_color

    @has_background_color.setter
    def has_background_color(self, has_background_color):
        """Sets the has_background_color of this DjvuProperties.

        Gets or sets a value indicating whether background color is used.  # noqa: E501

        :param has_background_color: The has_background_color of this DjvuProperties.  # noqa: E501
        :type: bool
        """
        if has_background_color is None:
            raise ValueError("Invalid value for `has_background_color`, must not be `None`")  # noqa: E501

        self._has_background_color = has_background_color

    @property
    def pages_count(self):
        """Gets the pages_count of this DjvuProperties.  # noqa: E501

        Gets or sets pages count.  # noqa: E501

        :return: The pages_count of this DjvuProperties.  # noqa: E501
        :rtype: int
        """
        return self._pages_count

    @pages_count.setter
    def pages_count(self, pages_count):
        """Sets the pages_count of this DjvuProperties.

        Gets or sets pages count.  # noqa: E501

        :param pages_count: The pages_count of this DjvuProperties.  # noqa: E501
        :type: int
        """
        if pages_count is None:
            raise ValueError("Invalid value for `pages_count`, must not be `None`")  # noqa: E501

        self._pages_count = pages_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DjvuProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DjvuProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
