# coding: utf-8

"""
    Aspose.Imaging Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ImageFeatures(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'image_id': 'str',
        'features_count': 'int',
        'feature_length_in_bits': 'int',
        'features': 'str'
    }

    attribute_map = {
        'image_id': 'ImageId',
        'features_count': 'FeaturesCount',
        'feature_length_in_bits': 'FeatureLengthInBits',
        'features': 'Features'
    }

    def __init__(self, image_id=None, features_count=None, feature_length_in_bits=None, features=None):  # noqa: E501
        """ImageFeatures - a model defined in Swagger"""  # noqa: E501

        self._image_id = None
        self._features_count = None
        self._feature_length_in_bits = None
        self._features = None
        self.discriminator = None

        if image_id is not None:
            self.image_id = image_id
        self.features_count = features_count
        self.feature_length_in_bits = feature_length_in_bits
        if features is not None:
            self.features = features

    @property
    def image_id(self):
        """Gets the image_id of this ImageFeatures.  # noqa: E501

        Gets the image identifier.  # noqa: E501

        :return: The image_id of this ImageFeatures.  # noqa: E501
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id):
        """Sets the image_id of this ImageFeatures.

        Gets the image identifier.  # noqa: E501

        :param image_id: The image_id of this ImageFeatures.  # noqa: E501
        :type: str
        """

        self._image_id = image_id

    @property
    def features_count(self):
        """Gets the features_count of this ImageFeatures.  # noqa: E501

        Gets the features count.  # noqa: E501

        :return: The features_count of this ImageFeatures.  # noqa: E501
        :rtype: int
        """
        return self._features_count

    @features_count.setter
    def features_count(self, features_count):
        """Sets the features_count of this ImageFeatures.

        Gets the features count.  # noqa: E501

        :param features_count: The features_count of this ImageFeatures.  # noqa: E501
        :type: int
        """
        if features_count is None:
            raise ValueError("Invalid value for `features_count`, must not be `None`")  # noqa: E501

        self._features_count = features_count

    @property
    def feature_length_in_bits(self):
        """Gets the feature_length_in_bits of this ImageFeatures.  # noqa: E501

        Gets the feature length in bits.  # noqa: E501

        :return: The feature_length_in_bits of this ImageFeatures.  # noqa: E501
        :rtype: int
        """
        return self._feature_length_in_bits

    @feature_length_in_bits.setter
    def feature_length_in_bits(self, feature_length_in_bits):
        """Sets the feature_length_in_bits of this ImageFeatures.

        Gets the feature length in bits.  # noqa: E501

        :param feature_length_in_bits: The feature_length_in_bits of this ImageFeatures.  # noqa: E501
        :type: int
        """
        if feature_length_in_bits is None:
            raise ValueError("Invalid value for `feature_length_in_bits`, must not be `None`")  # noqa: E501

        self._feature_length_in_bits = feature_length_in_bits

    @property
    def features(self):
        """Gets the features of this ImageFeatures.  # noqa: E501

        Gets the features.  # noqa: E501

        :return: The features of this ImageFeatures.  # noqa: E501
        :rtype: str
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this ImageFeatures.

        Gets the features.  # noqa: E501

        :param features: The features of this ImageFeatures.  # noqa: E501
        :type: str
        """
        if features is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', features):  # noqa: E501
            raise ValueError(r"Invalid value for `features`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._features = features

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageFeatures, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageFeatures):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
